# Generated by Django 4.1.6 on 2023-02-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_delivery', '0002_package_comment_package_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivery_status',
            field=models.CharField(choices=[('Still at station', 'Still at Station'), ('On transit', 'On Transit'), ('Arrived in destination', 'Arrived in Destination'), ('Delivered', 'Delivered')], default='Still at station', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='track_id',
            field=models.CharField(default='mrSKMMzGxcOk', max_length=500, unique=True),
        ),
    ]
