# Generated by Django 4.1.6 on 2023-02-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('receive_date', models.DateField()),
                ('short_description', models.TextField()),
                ('track_id', models.CharField(default='mIenCz4PlhCX', max_length=500, unique=True)),
                ('owner', models.CharField(max_length=500)),
                ('destination_address', models.CharField(max_length=500)),
                ('destination_country', models.CharField(max_length=500)),
                ('arrival_date', models.DateTimeField(max_length=500)),
            ],
        ),
    ]
