# Generated by Django 4.1.6 on 2023-02-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_delivery', '0003_alter_package_delivery_status_alter_package_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='track_id',
            field=models.CharField(default='m64U8lM6BBLH', max_length=500, unique=True),
        ),
    ]
