# Generated by Django 4.1.6 on 2023-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_delivery', '0004_alter_package_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivery_status',
            field=models.CharField(choices=[('Still at station', 'Still at Station'), ('On transit', 'On Transit'), ('On hold', 'On Hold'), ('Arrived in destination', 'Arrived in Destination'), ('Delivered', 'Delivered')], default='Still at station', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='track_id',
            field=models.CharField(default='xseDmu6gNmOs', max_length=500, unique=True),
        ),
    ]
