# Generated by Django 4.1.6 on 2023-02-15 20:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('track_delivery', '0005_alter_package_delivery_status_alter_package_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='current_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='arrival_date',
            field=models.DateTimeField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='track_id',
            field=models.CharField(default='Up5OefYj0ULDBMK', max_length=500, unique=True),
        ),
    ]
