# Generated by Django 4.1.6 on 2023-02-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_delivery', '0006_package_current_location_package_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='receive_date',
        ),
        migrations.AlterField(
            model_name='package',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='track_id',
            field=models.CharField(default='pFCsUW8ONUL6BMK', max_length=500, unique=True),
        ),
    ]
